# Generated by Django 5.2.7 on 2025-10-12 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('precheck', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatcheck',
            name='document_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='format_checks', to='submissions.documentversion'),
        ),
    ]
