# Generated by Django 5.2.7 on 2025-10-12 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('precheck', '0002_initial'),
        ('submissions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatcheck',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_format_checks', to='users.profile'),
        ),
        migrations.AddField(
            model_name='formatcheck',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='format_checks', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='plagiarismreport',
            name='document_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_reports', to='submissions.documentversion'),
        ),
        migrations.AddField(
            model_name='plagiarismreport',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_plagiarism_reports', to='users.profile'),
        ),
        migrations.AddField(
            model_name='plagiarismreport',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_reports', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='requirementcheck',
            name='related_documents',
            field=models.ManyToManyField(blank=True, related_name='requirement_checks', to='submissions.documentversion'),
        ),
        migrations.AddField(
            model_name='requirementcheck',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requirements', to='users.profile'),
        ),
        migrations.AddField(
            model_name='requirementcheck',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_checks', to='submissions.submission'),
        ),
        migrations.AddIndex(
            model_name='formatcheck',
            index=models.Index(fields=['submission', 'check_type'], name='precheck_fo_submiss_4980ba_idx'),
        ),
        migrations.AddIndex(
            model_name='formatcheck',
            index=models.Index(fields=['document_version', 'check_type'], name='precheck_fo_documen_e244c7_idx'),
        ),
        migrations.AddIndex(
            model_name='formatcheck',
            index=models.Index(fields=['status', 'created_at'], name='precheck_fo_status_2e2a08_idx'),
        ),
        migrations.AddIndex(
            model_name='formatcheck',
            index=models.Index(fields=['is_compliant'], name='precheck_fo_is_comp_39ae09_idx'),
        ),
        migrations.AddIndex(
            model_name='plagiarismreport',
            index=models.Index(fields=['submission', 'status'], name='precheck_pl_submiss_8fe763_idx'),
        ),
        migrations.AddIndex(
            model_name='plagiarismreport',
            index=models.Index(fields=['document_version'], name='precheck_pl_documen_394bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='plagiarismreport',
            index=models.Index(fields=['provider', 'provider_report_id'], name='precheck_pl_provide_d46e99_idx'),
        ),
        migrations.AddIndex(
            model_name='plagiarismreport',
            index=models.Index(fields=['similarity_score'], name='precheck_pl_similar_a73f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='plagiarismreport',
            index=models.Index(fields=['status', 'created_at'], name='precheck_pl_status_065369_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementcheck',
            index=models.Index(fields=['submission', 'status'], name='precheck_re_submiss_e32b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementcheck',
            index=models.Index(fields=['requirement_type', 'is_fulfilled'], name='precheck_re_require_5d4d06_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementcheck',
            index=models.Index(fields=['reviewed_by'], name='precheck_re_reviewe_a7b76f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requirementcheck',
            unique_together={('submission', 'requirement_type')},
        ),
    ]
