# Generated by Django 5.2.8 on 2025-12-21 09:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journals', '0009_alter_journalstaff_role'),
        ('users', '0011_alter_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('award_type', models.CharField(choices=[('BEST_REVIEWER', 'Best Reviewer'), ('RESEARCHER_OF_YEAR', 'Researcher of the Year'), ('TOP_CONTRIBUTOR', 'Top Contributor'), ('EXCELLENCE_REVIEW', 'Excellence in Review'), ('RISING_STAR', 'Rising Star'), ('LIFETIME_ACHIEVEMENT', 'Lifetime Achievement')], max_length=50)),
                ('year', models.IntegerField()),
                ('discipline', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('citation', models.TextField(blank=True)),
                ('metrics', models.JSONField(default=dict, help_text='Metrics that led to the award')),
                ('certificate_generated', models.BooleanField(default=False)),
                ('certificate_url', models.URLField(blank=True, null=True)),
                ('announced_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(blank=True, help_text='If null, award is global', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='journals.journal')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards_received', to='users.profile')),
            ],
            options={
                'ordering': ['-year', '-announced_at'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('badge_type', models.CharField(choices=[('REVIEWER', 'Reviewer Badge'), ('AUTHOR', 'Author Badge'), ('EDITOR', 'Editor Badge'), ('CONTRIBUTOR', 'Contributor Badge')], max_length=50)),
                ('level', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond')], default='BRONZE', max_length=20)),
                ('criteria', models.JSONField(default=dict, help_text="Criteria for earning this badge (e.g., {'reviews_completed': 10})")),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('icon_color', models.CharField(default='#FFD700', max_length=7)),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['badge_type', 'level', 'name'],
                'indexes': [models.Index(fields=['badge_type', 'is_active'], name='achievement_badge_t_87ab1e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('REVIEWER', 'Top Reviewers'), ('AUTHOR', 'Top Authors'), ('CITATIONS', 'Most Cited'), ('CONTRIBUTIONS', 'Top Contributors')], max_length=50)),
                ('period', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('ALL_TIME', 'All Time')], max_length=20)),
                ('field', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('metrics', models.JSONField(default=dict, help_text='Detailed metrics for the ranking')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='journals.journal')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='users.profile')),
            ],
            options={
                'ordering': ['period_end', 'category', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(default=2025)),
                ('achievement_data', models.JSONField(default=dict, help_text='Data about how the badge was earned')),
                ('is_featured', models.BooleanField(default=False)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='achievements.badge')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_badges', to='journals.journal')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='users.profile')),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(choices=[('AWARD', 'Award Certificate'), ('BADGE', 'Badge Certificate'), ('RECOGNITION', 'Recognition Certificate'), ('PARTICIPATION', 'Participation Certificate')], max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('pdf_generated', models.BooleanField(default=False)),
                ('template_name', models.CharField(default='default', max_length=100)),
                ('custom_data', models.JSONField(default=dict, help_text='Additional data for certificate generation')),
                ('verification_code', models.CharField(max_length=100, unique=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='achievements.award')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates_issued', to='journals.journal')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='users.profile')),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='achievements.userbadge')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.AddIndex(
            model_name='award',
            index=models.Index(fields=['year', 'award_type'], name='achievement_year_dffb51_idx'),
        ),
        migrations.AddIndex(
            model_name='award',
            index=models.Index(fields=['journal', 'year'], name='achievement_journal_58f0cc_idx'),
        ),
        migrations.AddIndex(
            model_name='award',
            index=models.Index(fields=['recipient'], name='achievement_recipie_ad512a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='award',
            unique_together={('journal', 'award_type', 'year', 'discipline', 'country')},
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['category', 'period', '-score'], name='achievement_categor_acb9da_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['journal', 'category', 'period'], name='achievement_journal_6e2542_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['field', 'category', 'period'], name='achievement_field_424094_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['country', 'category', 'period'], name='achievement_country_6efb68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboard',
            unique_together={('profile', 'category', 'period', 'period_start', 'period_end', 'journal', 'field', 'country')},
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['profile', '-earned_at'], name='achievement_profile_44376b_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['badge', 'year'], name='achievement_badge_i_19b4e6_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['recipient', '-issued_date'], name='achievement_recipie_07aaf2_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['verification_code'], name='achievement_verific_948052_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_number'], name='achievement_certifi_95c5d4_idx'),
        ),
    ]
