# Generated by Django 5.2.7 on 2025-10-12 10:06

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journals', '0002_initial'),
        ('submissions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorcontribution',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='users.profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='submissions.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comments', to='users.profile'),
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to='users.profile'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_versions', to='users.profile'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='submissions.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submissions.documentversion'),
        ),
        migrations.AddField(
            model_name='comment',
            name='document_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='submissions.documentversion'),
        ),
        migrations.AddField(
            model_name='submission',
            name='coauthors',
            field=models.ManyToManyField(blank=True, related_name='coauthored_submissions', through='submissions.AuthorContribution', to='users.profile'),
        ),
        migrations.AddField(
            model_name='submission',
            name='corresponding_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corresponding_submissions', to='users.profile'),
        ),
        migrations.AddField(
            model_name='submission',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='journals.journal'),
        ),
        migrations.AddField(
            model_name='document',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='authorcontribution',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_contributions', to='submissions.submission'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', 'version_number'], name='submissions_documen_0ccc1a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['file_hash'], name='submissions_file_ha_bf1fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['is_current'], name='submissions_is_curr_1045c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['document_version', 'resolved'], name='submissions_documen_dd4757_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='submissions_author__95c738_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='submissions_created_f80cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['journal', 'status'], name='submissions_journal_4ace6c_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['corresponding_author'], name='submissions_corresp_2b964d_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'submitted_at'], name='submissions_status_37dcdc_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['created_at'], name='submissions_created_d3a853_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='submissions_search__0ab6a0_gin'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata_json'], name='submissions_metadat_758ce8_gin'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['submission', 'document_type'], name='submissions_submiss_fc3918_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_by'], name='submissions_created_7c51bb_idx'),
        ),
        migrations.AddIndex(
            model_name='authorcontribution',
            index=models.Index(fields=['submission', 'order'], name='submissions_submiss_e72936_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='authorcontribution',
            unique_together={('submission', 'profile')},
        ),
    ]
