# Generated by Django 4.2 on 2025-10-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
