# Generated by Django 4.2 on 2025-10-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_fix_submission_number_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='review_type',
            field=models.CharField(choices=[('SINGLE_BLIND', 'Single Blind'), ('DOUBLE_BLIND', 'Double Blind'), ('OPEN', 'Open Review')], default='SINGLE_BLIND', help_text='Type of peer review for this submission', max_length=20),
        ),
    ]
