# Generated by Django 4.2 on 2025-11-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_journal_last_synced_at_journal_ojs_api_key_and_more'),
        ('submissions', '0004_submission_review_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ojs_id',
            field=models.IntegerField(blank=True, help_text='Open Journal Systems submission ID for this journal', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('ojs_id', 'journal')},
        ),
    ]
