# Generated by Django 4.2 on 2025-11-14 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_change_requested_role_to_array'),
        ('submissions', '0005_submission_ojs_id_alter_submission_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='current_version',
        ),
        migrations.RemoveField(
            model_name='document',
            name='editor_session_id',
        ),
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='document',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_documents', to='users.profile'),
        ),
        migrations.AddField(
            model_name='document',
            name='original_file',
            field=models.FileField(blank=True, help_text='Original uploaded DOCX file', null=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='document',
            name='yjs_state',
            field=models.BinaryField(blank=True, help_text='Binary Yjs state containing document content, versions, and comments', null=True),
        ),
    ]
