# Generated by Django 4.2 on 2025-11-17 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_category_section_researchtype_category_section_area_and_more'),
        ('submissions', '0006_superdoc_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Specific research area', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='journals.area'),
        ),
        migrations.AddField(
            model_name='submission',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category within the section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='journals.category'),
        ),
        migrations.AddField(
            model_name='submission',
            name='research_type',
            field=models.ForeignKey(blank=True, help_text='Type of research (Original, Review, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='journals.researchtype'),
        ),
        migrations.AddField(
            model_name='submission',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Journal section for this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='journals.section'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['section', 'category'], name='submissions_section_fc6d91_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['research_type', 'area'], name='submissions_researc_e4ea02_idx'),
        ),
    ]
