# Generated by Django 5.2.7 on 2025-11-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_submission_area_submission_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('REVISION_REQUESTED', 'Revision Requested'), ('REVISION_REQUIRED', 'Revision Required'), ('REVISED', 'Revised'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20),
        ),
    ]
