# Generated by Django 5.2.7 on 2025-12-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_alter_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional version metadata (e.g., anonymization status)'),
        ),
    ]
