# Generated by Django 5.2.7 on 2025-12-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_alter_submission_status'),
        ('submissions', '0009_documentversion_metadata'),
    ]

    operations = [
    ]
