# Generated by Django 5.2.7 on 2025-12-02 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_documentversion_metadata'),
        ('users', '0008_customuser_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='corresponding_author',
            field=models.ForeignKey(blank=True, help_text='Corresponding author profile (required for manual submissions, can be null for OJS imports)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corresponding_submissions', to='users.profile'),
        ),
    ]
