# Generated by Django 5.2.7 on 2025-12-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_allow_null_corresponding_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='original_file',
            field=models.FileField(blank=True, help_text='Original uploaded DOCX file', max_length=500, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
