# Generated by Django 5.2.7 on 2025-12-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_allow_null_corresponding_author'),
        ('submissions', '0010_merge_20251201_1345'),
    ]

    operations = [
    ]
