# Generated by Django 5.2.7 on 2025-12-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_alter_document_original_file'),
        ('submissions', '0011_merge_20251202_1520'),
    ]

    operations = [
    ]
