# Generated by Django 5.2.7 on 2025-12-09 05:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0012_merge_20251203_1415'),
        ('users', '0010_customuser_imported_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('REVISION_REQUESTED', 'Revision Requested'), ('REVISION_REQUIRED', 'Revision Required'), ('REVISED', 'Revised'), ('ACCEPTANCE_REQUESTED', 'Acceptance Requested'), ('REJECTION_REQUESTED', 'Rejection Requested'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('COPYEDITING', 'Copyediting'), ('IN_PRODUCTION', 'In Production'), ('SCHEDULED', 'Scheduled for Publication'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='CopyeditingAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(help_text='Deadline for copyediting completion')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions from editor to copyeditor')),
                ('completion_notes', models.TextField(blank=True, help_text='Notes from copyeditor upon completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(help_text='Editor who assigned the copyeditor', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_copyediting_tasks', to='users.profile')),
                ('copyeditor', models.ForeignKey(help_text='Copyeditor assigned to this submission', on_delete=django.db.models.deletion.CASCADE, related_name='copyediting_assignments', to='users.profile')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copyediting_assignments', to='submissions.submission')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='CopyeditingDiscussion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='submissions.copyeditingassignment')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_copyediting_discussions', to='users.profile')),
                ('participants', models.ManyToManyField(help_text='Users involved in this discussion', related_name='copyediting_discussions', to='users.profile')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_copyediting_discussions', to='users.profile')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copyediting_discussions', to='submissions.submission')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CopyeditingFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('DRAFT', 'Draft File'), ('COPYEDITED', 'Copyedited File'), ('FINAL', 'Final Approved')], max_length=20)),
                ('file', models.FileField(help_text='Copyediting file (draft or edited version)', upload_to='copyediting/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_copyediting_files', to='users.profile')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='submissions.copyeditingassignment')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copyediting_files', to='submissions.submission')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_copyediting_files', to='users.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CopyeditingMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(help_text='Message content (supports HTML)')),
                ('has_attachments', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copyediting_messages', to='users.profile')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='submissions.copyeditingdiscussion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CopyeditingMessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Discussion attachment file', upload_to='copyediting/discussions/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='submissions.copyeditingmessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(help_text='Deadline for production completion')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions from editor to production assistant')),
                ('completion_notes', models.TextField(blank=True, help_text='Notes from production assistant upon completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(help_text='Editor who assigned the production assistant', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_production_tasks', to='users.profile')),
                ('production_assistant', models.ForeignKey(help_text='Production assistant or layout editor assigned', on_delete=django.db.models.deletion.CASCADE, related_name='production_assignments', to='users.profile')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_assignments', to='submissions.submission')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionDiscussion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='submissions.productionassignment')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_production_discussions', to='users.profile')),
                ('participants', models.ManyToManyField(help_text='Users involved in this discussion', related_name='production_discussions', to='users.profile')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_production_discussions', to='users.profile')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_discussions', to='submissions.submission')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('PRODUCTION_READY', 'Production Ready'), ('GALLEY', 'Galley File')], max_length=20)),
                ('galley_format', models.CharField(blank=True, choices=[('PDF', 'PDF'), ('HTML', 'HTML'), ('XML', 'XML'), ('EPUB', 'EPUB'), ('MOBI', 'MOBI'), ('OTHER', 'Other')], help_text='Format for galley files', max_length=20, null=True)),
                ('file', models.FileField(help_text='Production file (ready file or galley)', upload_to='production/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('label', models.CharField(help_text="Display label for the galley (e.g., 'PDF', 'Full Text HTML')", max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False, help_text='Whether this galley is published and visible to readers')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_production_files', to='users.profile')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='submissions.productionassignment')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_files', to='submissions.submission')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_production_files', to='users.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(help_text='Message content (supports HTML)')),
                ('has_attachments', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_messages', to='users.profile')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='submissions.productiondiscussion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionMessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Discussion attachment file', upload_to='production/discussions/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='submissions.productionmessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('scheduled_date', models.DateTimeField(help_text='Date and time when article should be published')),
                ('published_date', models.DateTimeField(blank=True, help_text='Actual publication date', null=True)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('issue', models.CharField(blank=True, max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('doi', models.CharField(blank=True, help_text='Digital Object Identifier', max_length=255)),
                ('pages', models.CharField(blank=True, help_text="Page range (e.g., '123-145')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_publications', to='users.profile')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication_schedule', to='submissions.submission')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AddIndex(
            model_name='copyeditingassignment',
            index=models.Index(fields=['submission', 'status'], name='submissions_submiss_350e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='copyeditingassignment',
            index=models.Index(fields=['copyeditor', 'status'], name='submissions_copyedi_c24b59_idx'),
        ),
        migrations.AddIndex(
            model_name='copyeditingassignment',
            index=models.Index(fields=['status', 'due_date'], name='submissions_status_8a8dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='copyeditingdiscussion',
            index=models.Index(fields=['assignment', 'status'], name='submissions_assignm_b593f9_idx'),
        ),
        migrations.AddIndex(
            model_name='copyeditingdiscussion',
            index=models.Index(fields=['submission', 'status'], name='submissions_submiss_642263_idx'),
        ),
        migrations.AddIndex(
            model_name='copyeditingdiscussion',
            index=models.Index(fields=['started_by'], name='submissions_started_8b430a_idx'),
        ),
        migrations.AddIndex(
            model_name='copyeditingfile',
            index=models.Index(fields=['assignment', 'file_type'], name='submissions_assignm_53f2b9_idx'),
        ),
        migrations.AddIndex(
            model_name='copyeditingfile',
            index=models.Index(fields=['submission', 'file_type'], name='submissions_submiss_03da17_idx'),
        ),
        migrations.AddIndex(
            model_name='copyeditingfile',
            index=models.Index(fields=['uploaded_by'], name='submissions_uploade_ae1eae_idx'),
        ),
        migrations.AddIndex(
            model_name='copyeditingmessage',
            index=models.Index(fields=['discussion', 'created_at'], name='submissions_discuss_74349b_idx'),
        ),
        migrations.AddIndex(
            model_name='copyeditingmessage',
            index=models.Index(fields=['author'], name='submissions_author__4faa52_idx'),
        ),
        migrations.AddIndex(
            model_name='productionassignment',
            index=models.Index(fields=['submission', 'status'], name='submissions_submiss_526ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='productionassignment',
            index=models.Index(fields=['production_assistant', 'status'], name='submissions_product_c3c30b_idx'),
        ),
        migrations.AddIndex(
            model_name='productionassignment',
            index=models.Index(fields=['status', 'due_date'], name='submissions_status_9cb550_idx'),
        ),
        migrations.AddIndex(
            model_name='productiondiscussion',
            index=models.Index(fields=['assignment', 'status'], name='submissions_assignm_a539b1_idx'),
        ),
        migrations.AddIndex(
            model_name='productiondiscussion',
            index=models.Index(fields=['submission', 'status'], name='submissions_submiss_3436a6_idx'),
        ),
        migrations.AddIndex(
            model_name='productiondiscussion',
            index=models.Index(fields=['started_by'], name='submissions_started_494042_idx'),
        ),
        migrations.AddIndex(
            model_name='productionfile',
            index=models.Index(fields=['assignment', 'file_type'], name='submissions_assignm_affbe1_idx'),
        ),
        migrations.AddIndex(
            model_name='productionfile',
            index=models.Index(fields=['submission', 'file_type', 'is_published'], name='submissions_submiss_76502d_idx'),
        ),
        migrations.AddIndex(
            model_name='productionfile',
            index=models.Index(fields=['uploaded_by'], name='submissions_uploade_f0d363_idx'),
        ),
        migrations.AddIndex(
            model_name='productionmessage',
            index=models.Index(fields=['discussion', 'created_at'], name='submissions_discuss_90a768_idx'),
        ),
        migrations.AddIndex(
            model_name='productionmessage',
            index=models.Index(fields=['author'], name='submissions_author__f3994f_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationschedule',
            index=models.Index(fields=['submission', 'status'], name='submissions_submiss_19581e_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationschedule',
            index=models.Index(fields=['status', 'scheduled_date'], name='submissions_status_e2a768_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationschedule',
            index=models.Index(fields=['scheduled_by'], name='submissions_schedul_50c0e9_idx'),
        ),
    ]
