# Generated by Django 5.2.8 on 2025-12-09 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_alter_submission_status_copyeditingassignment_and_more'),
        ('users', '0010_customuser_imported_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to='users.profile'),
        ),
    ]
