# Generated by Django 5.2.8 on 2025-12-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0014_document_created_by_set_null'),
        ('users', '0010_customuser_imported_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyeditingassignment',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Additional users who can collaborate on this assignment', related_name='participating_copyediting_assignments', to='users.profile'),
        ),
    ]
