# Generated by Django 5.2.8 on 2025-12-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0015_add_participants_to_copyediting_assignment'),
        ('users', '0010_customuser_imported_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyeditingfile',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='copyeditingfile',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, help_text='Last person to edit this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_copyediting_files', to='users.profile'),
        ),
    ]
