# Generated by Django 5.2.7 on 2025-12-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0016_add_edit_tracking_to_copyediting_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyeditingfile',
            name='file_type',
            field=models.CharField(choices=[('DRAFT', 'Draft File'), ('COPYEDITED', 'Copyedited File'), ('AUTHOR_FINAL', 'Author Confirmed Final'), ('FINAL', 'Final Approved')], max_length=20),
        ),
    ]
