# Generated by Django 5.2.8 on 2025-12-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0017_add_author_final_file_type'),
        ('users', '0010_customuser_imported_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionassignment',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Additional participants involved in this production assignment', related_name='production_participants', to='users.profile'),
        ),
    ]
