# Generated by Django 5.2.8 on 2025-12-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0018_add_participants_to_production_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='doi',
            field=models.CharField(blank=True, help_text='Digital Object Identifier (e.g., 10.1234/example.2024.001)', max_length=255, null=True, unique=True),
        ),
    ]
