# Generated by Django 5.2.7 on 2025-10-12 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojsmapping',
            name='local_submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ojs_mapping', to='submissions.submission'),
        ),
    ]
