# Generated by Django 5.2.7 on 2025-10-12 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcidintegration',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orcid_integration', to='users.profile'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='external_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.externalserviceintegration'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_syncs', to='users.profile'),
        ),
        migrations.AddIndex(
            model_name='ojsmapping',
            index=models.Index(fields=['ojs_submission_id', 'ojs_instance_url'], name='integration_ojs_sub_41a3b1_idx'),
        ),
        migrations.AddIndex(
            model_name='ojsmapping',
            index=models.Index(fields=['sync_status', 'last_synced_at'], name='integration_sync_st_c563b6_idx'),
        ),
        migrations.AddIndex(
            model_name='ojsmapping',
            index=models.Index(fields=['local_submission'], name='integration_local_s_b51c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='orcidintegration',
            index=models.Index(fields=['orcid_id'], name='integration_orcid_i_e75678_idx'),
        ),
        migrations.AddIndex(
            model_name='orcidintegration',
            index=models.Index(fields=['status'], name='integration_status_31d427_idx'),
        ),
        migrations.AddIndex(
            model_name='orcidintegration',
            index=models.Index(fields=['last_sync_at'], name='integration_last_sy_4dc7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['sync_type', 'status'], name='integration_sync_ty_6f0d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['external_service', 'started_at'], name='integration_externa_97d794_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='integration_resourc_438932_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['status', 'started_at'], name='integration_status_c4341d_idx'),
        ),
    ]
