# Generated by Django 4.2 on 2025-10-15 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORCIDOAuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_token', models.CharField(db_index=True, help_text='Unique state token for OAuth flow', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='State token expiration time (usually 10 minutes)')),
                ('used', models.BooleanField(default=False, help_text='Whether this state token has been used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcid_oauth_states', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='orcidoauthstate',
            index=models.Index(fields=['state_token', 'used'], name='integration_state_t_b4464b_idx'),
        ),
        migrations.AddIndex(
            model_name='orcidoauthstate',
            index=models.Index(fields=['expires_at', 'used'], name='integration_expires_5692a2_idx'),
        ),
    ]
