# Generated by Django 5.2.7 on 2025-12-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_orcidoauthstate_and_more'),
        ('submissions', '0009_documentversion_metadata'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ojsmapping',
            name='integration_ojs_sub_41a3b1_idx',
        ),
        migrations.RemoveField(
            model_name='ojsmapping',
            name='ojs_instance_url',
        ),
        migrations.AddIndex(
            model_name='ojsmapping',
            index=models.Index(fields=['ojs_submission_id'], name='integration_ojs_sub_9803b8_idx'),
        ),
    ]
