# Generated by Django 5.2.7 on 2025-10-12 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('submissions', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomalyevent',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_anomalies', to='users.profile'),
        ),
        migrations.AddField(
            model_name='award',
            name='awarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_awards', to='users.profile'),
        ),
        migrations.AddField(
            model_name='award',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='users.profile'),
        ),
        migrations.AddField(
            model_name='concept',
            name='parent_concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_concepts', to='common.concept'),
        ),
        migrations.AddField(
            model_name='concept',
            name='related_concepts',
            field=models.ManyToManyField(blank=True, to='common.concept'),
        ),
        migrations.AddIndex(
            model_name='embedding',
            index=models.Index(fields=['embedding_type', 'source_id'], name='common_embe_embeddi_49f0b5_idx'),
        ),
        migrations.AddIndex(
            model_name='embedding',
            index=models.Index(fields=['vector_hash'], name='common_embe_vector__8a3f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='embedding',
            index=models.Index(fields=['model_name', 'model_version'], name='common_embe_model_n_b1d498_idx'),
        ),
        migrations.AddIndex(
            model_name='embedding',
            index=models.Index(fields=['vector_store_id'], name='common_embe_vector__85cadb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='embedding',
            unique_together={('embedding_type', 'source_id', 'model_name')},
        ),
        migrations.AddField(
            model_name='concept',
            name='embedding',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concept', to='common.embedding'),
        ),
        migrations.AddField(
            model_name='verificationticket',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tickets', to='users.profile'),
        ),
        migrations.AddField(
            model_name='verificationticket',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verification_tickets', to='users.profile'),
        ),
        migrations.AddField(
            model_name='verificationticket',
            name='supporting_documents',
            field=models.ManyToManyField(blank=True, related_name='verification_tickets', to='submissions.documentversion'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'created_at'], name='common_acti_user_id_2e4fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action_type', 'resource_type'], name='common_acti_action__32c57d_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='common_acti_resourc_3aa9da_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='common_acti_created_3a96f8_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['ip_address'], name='common_acti_ip_addr_3fffa6_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['event_type', 'severity'], name='common_anom_event_t_25bd15_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['resource_type', 'resource_id'], name='common_anom_resourc_efe06b_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['anomaly_score'], name='common_anom_anomaly_4bb685_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['is_handled', 'severity'], name='common_anom_is_hand_91c372_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['created_at'], name='common_anom_created_b5b2c1_idx'),
        ),
        migrations.AddIndex(
            model_name='award',
            index=models.Index(fields=['profile', 'badge_type'], name='common_awar_profile_453669_idx'),
        ),
        migrations.AddIndex(
            model_name='award',
            index=models.Index(fields=['badge_type', 'awarded_at'], name='common_awar_badge_t_0f71fc_idx'),
        ),
        migrations.AddIndex(
            model_name='award',
            index=models.Index(fields=['is_public'], name='common_awar_is_publ_5e9001_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['provider', 'external_id'], name='common_conc_provide_39802c_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['parent_concept'], name='common_conc_parent__53dd98_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['usage_count'], name='common_conc_usage_c_58e489_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['name'], name='common_conc_name_d50605_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='concept',
            unique_together={('provider', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='verificationticket',
            index=models.Index(fields=['profile', 'status'], name='common_veri_profile_2e04a2_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationticket',
            index=models.Index(fields=['requested_role', 'status'], name='common_veri_request_9a8ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationticket',
            index=models.Index(fields=['reviewed_by'], name='common_veri_reviewe_4808d2_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationticket',
            index=models.Index(fields=['ml_score'], name='common_veri_ml_scor_7d14ba_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationticket',
            index=models.Index(fields=['created_at'], name='common_veri_created_38cce8_idx'),
        ),
    ]
