# Generated by Django 4.2 on 2025-11-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_verificationrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ojs_id_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="Map of journal ID to OJS user ID: {'journal_uuid': ojs_user_id}"),
        ),
    ]
