# Generated by Django 4.2 on 2025-11-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_ojs_id_mapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationrequest',
            name='supporting_documents',
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='supporting_letter',
            field=models.TextField(blank=True, help_text='Letter from supervisor or institution supporting the verification request'),
        ),
    ]
