# Generated by Django 4.2 on 2025-11-04 10:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_replace_supporting_documents_with_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationrequest',
            name='requested_role',
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='requested_roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AUTHOR', 'Author'), ('REVIEWER', 'Reviewer')], max_length=20), default=list, help_text="Roles being requested for verification (e.g., ['AUTHOR', 'REVIEWER'])", size=None),
        ),
    ]
