# Generated by Django 4.2 on 2025-11-17 05:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_change_requested_role_to_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='requested_roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AUTHOR', 'Author'), ('REVIEWER', 'Reviewer'), ('EDITOR', 'Editor')], max_length=20), default=list, help_text="Roles being requested for verification (e.g., ['AUTHOR', 'REVIEWER'])", size=None),
        ),
    ]
