# Generated by Django 5.2.7 on 2025-11-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_verificationrequest_requested_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Has the user verified their email address?'),
        ),
    ]
