# Generated by Django 5.2.7 on 2025-12-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='orcid_id',
            field=models.CharField(blank=True, help_text='ORCID identifier (e.g., 0000-0000-0000-0000) or full ORCID URL', max_length=100, null=True, unique=True),
        ),
    ]
