# Generated by Django 5.2.8 on 2025-12-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_increase_orcid_field_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='imported_from',
            field=models.UUIDField(blank=True, help_text='Journal ID from which this user was imported (OJS integration)', null=True),
        ),
    ]
