# Generated by Django 5.2.8 on 2025-12-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_imported_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('READER', 'Reader'), ('AUTHOR', 'Author'), ('REVIEWER', 'Reviewer'), ('EDITOR', 'Editor'), ('JOURNAL_MANAGER', 'Journal Manager'), ('ADMIN', 'Administrator')], max_length=50, unique=True),
        ),
    ]
