# Generated by Django 5.2.7 on 2025-10-12 10:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Full journal title', max_length=255)),
                ('short_name', models.CharField(help_text='Short name or abbreviation for the journal', max_length=50, unique=True)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('issn_print', models.CharField(blank=True, help_text='Print ISSN (e.g., 1234-5678)', max_length=9)),
                ('issn_online', models.CharField(blank=True, help_text='Online ISSN (e.g., 1234-5679)', max_length=9)),
                ('website_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('settings', models.JSONField(default=dict, help_text='Journal-specific settings and configuration')),
                ('is_active', models.BooleanField(default=True)),
                ('is_accepting_submissions', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='JournalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EDITOR_IN_CHIEF', 'Editor-in-Chief'), ('MANAGING_EDITOR', 'Managing Editor'), ('ASSOCIATE_EDITOR', 'Associate Editor'), ('GUEST_EDITOR', 'Guest Editor'), ('SECTION_EDITOR', 'Section Editor'), ('COPY_EDITOR', 'Copy Editor'), ('LAYOUT_EDITOR', 'Layout Editor'), ('PROOFREADER', 'Proofreader')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('permissions', models.JSONField(default=dict, help_text='Staff member specific permissions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='journals.journal')),
            ],
        ),
    ]
