# Generated by Django 5.2.7 on 2025-10-12 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journals', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalstaff',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_positions', to='users.profile'),
        ),
        migrations.AddField(
            model_name='journal',
            name='editor_group',
            field=models.ManyToManyField(blank=True, related_name='managed_journals', through='journals.JournalStaff', to='users.profile'),
        ),
        migrations.AddIndex(
            model_name='journalstaff',
            index=models.Index(fields=['journal', 'is_active'], name='journals_jo_journal_aa4891_idx'),
        ),
        migrations.AddIndex(
            model_name='journalstaff',
            index=models.Index(fields=['profile', 'is_active'], name='journals_jo_profile_45850e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalstaff',
            unique_together={('journal', 'profile', 'role')},
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['short_name'], name='journals_jo_short_n_aea838_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['is_active', 'is_accepting_submissions'], name='journals_jo_is_acti_332abd_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['created_at'], name='journals_jo_created_4dee08_idx'),
        ),
    ]
