# Generated by Django 5.2.7 on 2025-11-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last successful sync with OJS', null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='ojs_api_key',
            field=models.CharField(blank=True, help_text='API key for OJS authentication', max_length=255),
        ),
        migrations.AddField(
            model_name='journal',
            name='ojs_api_url',
            field=models.URLField(blank=True, help_text='OJS API base URL for this journal (e.g., https://journal.com/index.php/journal/api/v1)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='ojs_enabled',
            field=models.BooleanField(default=False, help_text='Enable OJS sync for this journal'),
        ),
        migrations.AddField(
            model_name='journal',
            name='ojs_journal_id',
            field=models.IntegerField(blank=True, help_text='Journal ID in OJS system', null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='sync_enabled',
            field=models.BooleanField(default=True, help_text='Enable automatic background sync for this journal'),
        ),
        migrations.AddField(
            model_name='journal',
            name='sync_interval_hours',
            field=models.IntegerField(default=1, help_text='Sync interval in hours (default: 1 hour)'),
        ),
    ]
