# Generated by Django 4.2 on 2025-11-17 05:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_verificationrequest_requested_roles'),
        ('journals', '0003_journal_last_synced_at_journal_ojs_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Category name', max_length=255)),
                ('code', models.CharField(help_text='Short code for category', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Section name', max_length=255)),
                ('code', models.CharField(help_text='Short code for section', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='journals.journal')),
                ('section_editor', models.ForeignKey(blank=True, help_text='Primary section editor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sections', to='users.profile')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Research type name', max_length=255)),
                ('code', models.CharField(help_text='Short code for research type', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.JSONField(default=dict, help_text='Specific requirements for this research type (word count, sections, etc.)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_types', to='journals.category')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='journals.section'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Area name', max_length=255)),
                ('code', models.CharField(help_text='Short code for area', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.JSONField(default=list, help_text='Keywords associated with this area for matching/recommendation')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='journals.researchtype')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['journal', 'is_active'], name='journals_se_journal_df6117_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('journal', 'code')},
        ),
        migrations.AddIndex(
            model_name='researchtype',
            index=models.Index(fields=['category', 'is_active'], name='journals_re_categor_02eb73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='researchtype',
            unique_together={('category', 'code')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['section', 'is_active'], name='journals_ca_section_68e746_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('section', 'code')},
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['research_type', 'is_active'], name='journals_ar_researc_27271f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('research_type', 'code')},
        ),
    ]
