# Generated by Django 4.2 on 2025-11-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_category_section_researchtype_category_section_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='main_contact_email',
            field=models.EmailField(blank=True, help_text='Main contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='journal',
            name='main_contact_name',
            field=models.CharField(blank=True, help_text='Main contact person name', max_length=255),
        ),
        migrations.AddField(
            model_name='journal',
            name='main_contact_phone',
            field=models.CharField(blank=True, help_text='Main contact phone number', max_length=50),
        ),
        migrations.AddField(
            model_name='journal',
            name='technical_contact_email',
            field=models.EmailField(blank=True, help_text='Technical contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='journal',
            name='technical_contact_name',
            field=models.CharField(blank=True, help_text='Technical contact person name', max_length=255),
        ),
        migrations.AddField(
            model_name='journal',
            name='technical_contact_phone',
            field=models.CharField(blank=True, help_text='Technical contact phone number', max_length=50),
        ),
    ]
