# Generated by Django 5.2.7 on 2025-11-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_journal_main_contact_email_journal_main_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalstaff',
            name='role',
            field=models.CharField(choices=[('EDITOR_IN_CHIEF', 'Editor-in-Chief'), ('MANAGING_EDITOR', 'Managing Editor'), ('ASSOCIATE_EDITOR', 'Associate Editor'), ('GUEST_EDITOR', 'Guest Editor'), ('SECTION_EDITOR', 'Section Editor'), ('REVIEWER', 'Reviewer'), ('COPY_EDITOR', 'Copy Editor'), ('LAYOUT_EDITOR', 'Layout Editor'), ('PROOFREADER', 'Proofreader')], max_length=50),
        ),
    ]
