# Generated by Django 5.2.7 on 2025-11-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0006_alter_journalstaff_role'),
    ]

    operations = [
    ]
