# Generated by Django 5.2.7 on 2025-12-02 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_migrate_settings_to_arrays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='last_synced_at',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='sync_enabled',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='sync_interval_hours',
        ),
    ]
