# Generated by Django 5.2.8 on 2025-12-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0008_remove_journal_last_synced_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalstaff',
            name='role',
            field=models.CharField(choices=[('EDITOR_IN_CHIEF', 'Editor-in-Chief'), ('MANAGING_EDITOR', 'Managing Editor'), ('JOURNAL_MANAGER', 'Journal Manager'), ('ASSOCIATE_EDITOR', 'Associate Editor'), ('GUEST_EDITOR', 'Guest Editor'), ('SECTION_EDITOR', 'Section Editor'), ('REVIEWER', 'Reviewer'), ('COPY_EDITOR', 'Copy Editor'), ('LAYOUT_EDITOR', 'Layout Editor'), ('PROOFREADER', 'Proofreader')], max_length=50),
        ),
    ]
