# Generated by Django 6.0 on 2026-03-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0010_replace_description_with_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='abstract_word_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum words allowed in abstract. 0 means no limit.'),
        ),
        migrations.AddField(
            model_name='section',
            name='author_policies',
            field=models.TextField(blank=True, help_text='Custom policies and rules for authors in this section'),
        ),
        migrations.AddField(
            model_name='section',
            name='max_authors',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of authors allowed per submission. 0 means no limit.'),
        ),
        migrations.AddField(
            model_name='section',
            name='max_figures',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of figures allowed per submission. 0 means no limit.'),
        ),
        migrations.AddField(
            model_name='section',
            name='max_tables',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of tables allowed per submission. 0 means no limit.'),
        ),
        migrations.AddField(
            model_name='section',
            name='min_authors',
            field=models.PositiveIntegerField(default=1, help_text='Minimum number of authors required per submission'),
        ),
        migrations.AddField(
            model_name='section',
            name='reviewer_policies',
            field=models.TextField(blank=True, help_text='Custom policies and rules for reviewers in this section'),
        ),
        migrations.AddField(
            model_name='section',
            name='total_word_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum total words including abstract, authorship, acknowledgements, and references. 0 means no limit.'),
        ),
    ]
