# Generated by Django 5.2.7 on 2025-10-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='attached_files',
            field=models.ManyToManyField(blank=True, related_name='reviews_with_attachments', to='submissions.documentversion'),
        ),
    ]
