# Generated by Django 5.2.7 on 2025-10-12 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0002_initial'),
        ('submissions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.profile'),
        ),
        migrations.AddField(
            model_name='review',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reviews', to='users.profile'),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='users.profile'),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='review',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reviews.reviewassignment'),
        ),
        migrations.AddField(
            model_name='reviewerrecommendation',
            name='recommended_reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_recommendations', to='users.profile'),
        ),
        migrations.AddField(
            model_name='reviewerrecommendation',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_recommendations', to='submissions.submission'),
        ),
        migrations.AddIndex(
            model_name='reviewassignment',
            index=models.Index(fields=['submission', 'status'], name='reviews_rev_submiss_5a95e7_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewassignment',
            index=models.Index(fields=['reviewer', 'status'], name='reviews_rev_reviewe_73b0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewassignment',
            index=models.Index(fields=['status', 'due_date'], name='reviews_rev_status_aac222_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewassignment',
            index=models.Index(fields=['assigned_by'], name='reviews_rev_assigne_1fd1d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewassignment',
            unique_together={('submission', 'reviewer', 'review_round')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['submission', 'recommendation'], name='reviews_rev_submiss_587d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer'], name='reviews_rev_reviewe_e817a5_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['submitted_at'], name='reviews_rev_submitt_dc56bd_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['assignment'], name='reviews_rev_assignm_49a7a4_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewerrecommendation',
            index=models.Index(fields=['submission', 'confidence_score'], name='reviews_rev_submiss_31fae1_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewerrecommendation',
            index=models.Index(fields=['recommended_reviewer'], name='reviews_rev_recomme_4369cd_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewerrecommendation',
            index=models.Index(fields=['is_used'], name='reviews_rev_is_used_60184d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewerrecommendation',
            unique_together={('submission', 'recommended_reviewer')},
        ),
    ]
