# Generated by Django 4.2 on 2025-10-16 08:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_verificationrequest_and_more'),
        ('journals', '0002_initial'),
        ('reviews', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('SINGLE_BLIND', 'Single Blind'), ('DOUBLE_BLIND', 'Double Blind'), ('OPEN', 'Open Review')], default='SINGLE_BLIND', help_text='Type of review (affects anonymity)', max_length=20),
        ),
        migrations.CreateModel(
            name='ReviewVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('content_snapshot', models.JSONField(help_text='JSON snapshot of review content at this version')),
                ('changes_made', models.TextField(blank=True, help_text='Description of changes made in this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_versions', to='users.profile')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='reviews.review')),
            ],
            options={
                'ordering': ['-version_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewFormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('form_schema', models.JSONField(default=dict, help_text='JSON schema defining review form fields and validation rules')),
                ('scoring_criteria', models.JSONField(default=dict, help_text='Scoring criteria configuration (names, weights, ranges)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(blank=True, help_text='Journal using this template (null for system default)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_templates', to='journals.journal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Attached file (PDF, DOC, DOCX, TXT only)', upload_to='review_attachments/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the attachment')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reviews.review')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_attachments', to='users.profile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='review',
            name='form_template',
            field=models.ForeignKey(blank=True, help_text='Review form template used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='reviews.reviewformtemplate'),
        ),
        migrations.AddIndex(
            model_name='reviewversion',
            index=models.Index(fields=['review', 'version_number'], name='reviews_rev_review__1e3e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewversion',
            index=models.Index(fields=['created_at'], name='reviews_rev_created_4df5d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewversion',
            unique_together={('review', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='reviewformtemplate',
            index=models.Index(fields=['journal', 'is_active'], name='reviews_rev_journal_42529c_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewformtemplate',
            index=models.Index(fields=['is_default'], name='reviews_rev_is_defa_232bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewattachment',
            index=models.Index(fields=['review'], name='reviews_rev_review__00dbb5_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewattachment',
            index=models.Index(fields=['uploaded_by'], name='reviews_rev_uploade_10b339_idx'),
        ),
    ]
