# Generated by Django 4.2 on 2025-11-21 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_decisionlettertemplate_editorialdecision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.reviewassignment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
