# Generated by Django 5.2.7 on 2025-11-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_decisionlettertemplate_editorialdecision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
