# Generated by Django 4.2 on 2025-11-21 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_change_review_assignment_to_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_round',
            field=models.PositiveIntegerField(default=1, help_text='Which revision round this review belongs to (1=initial, 2=first revision, etc.)'),
        ),
        migrations.AddField(
            model_name='review',
            name='revision_round',
            field=models.ForeignKey(blank=True, help_text='The revision round this review is for (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='reviews.revisionround'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['submission', 'review_round'], name='reviews_rev_submiss_e6c590_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['revision_round'], name='reviews_rev_revisio_2a7c76_idx'),
        ),
    ]
