# Generated by Django 5.2.7 on 2025-11-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_is_published'),
        ('reviews', '0007_add_review_round_tracking'),
    ]

    operations = [
    ]
