# Generated by Django 5.2.7 on 2025-12-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_reviewassignment_status_and_more'),
        ('reviews', '0008_merge_20251123_1203'),
    ]

    operations = [
    ]
