# Generated by Django 4.2 on 2025-10-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('WELCOME', 'Welcome Email'), ('EMAIL_VERIFICATION', 'Email Verification'), ('PASSWORD_RESET', 'Password Reset'), ('ORCID_CONNECTED', 'ORCID Connected'), ('ORCID_DISCONNECTED', 'ORCID Disconnected'), ('VERIFICATION_SUBMITTED', 'Verification Request Submitted'), ('VERIFICATION_APPROVED', 'Verification Request Approved'), ('VERIFICATION_REJECTED', 'Verification Request Rejected'), ('VERIFICATION_INFO_REQUESTED', 'Additional Information Requested'), ('VERIFICATION_USER_RESPONDED', 'User Responded to Info Request'), ('SUBMISSION_RECEIVED', 'Submission Received'), ('REVIEW_ASSIGNED', 'Review Assigned'), ('REVIEW_COMPLETED', 'Review Completed'), ('DECISION_MADE', 'Editorial Decision'), ('REVIEW_INVITATION', 'Review Invitation'), ('REVIEW_REMINDER', 'Review Deadline Reminder'), ('REVIEW_SUBMITTED', 'Review Submitted Confirmation'), ('EDITORIAL_DECISION_ACCEPT', 'Manuscript Accepted'), ('EDITORIAL_DECISION_REJECT', 'Manuscript Rejected'), ('REVISION_REQUESTED', 'Revisions Requested')], help_text='Type of email template', max_length=50, unique=True),
        ),
    ]
