# Generated by Django 5.2.7 on 2025-12-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_emailtemplate_template_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotificationpreference',
            name='email_on_copyediting_assigned',
            field=models.BooleanField(default=True, help_text='Notify when copyediting is assigned'),
        ),
        migrations.AddField(
            model_name='emailnotificationpreference',
            name='email_on_copyediting_completed',
            field=models.BooleanField(default=True, help_text='Notify when copyediting is completed'),
        ),
        migrations.AddField(
            model_name='emailnotificationpreference',
            name='email_on_production_assigned',
            field=models.BooleanField(default=True, help_text='Notify when production is assigned'),
        ),
        migrations.AddField(
            model_name='emailnotificationpreference',
            name='email_on_production_completed',
            field=models.BooleanField(default=True, help_text='Notify when production is completed'),
        ),
        migrations.AddField(
            model_name='emailnotificationpreference',
            name='email_on_publication_published',
            field=models.BooleanField(default=True, help_text='Notify when article is published'),
        ),
        migrations.AddField(
            model_name='emailnotificationpreference',
            name='email_on_publication_scheduled',
            field=models.BooleanField(default=True, help_text='Notify when publication is scheduled'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('WELCOME', 'Welcome Email'), ('EMAIL_VERIFICATION', 'Email Verification'), ('PASSWORD_RESET', 'Password Reset'), ('ORCID_CONNECTED', 'ORCID Connected'), ('ORCID_DISCONNECTED', 'ORCID Disconnected'), ('VERIFICATION_SUBMITTED', 'Verification Request Submitted'), ('VERIFICATION_APPROVED', 'Verification Request Approved'), ('VERIFICATION_REJECTED', 'Verification Request Rejected'), ('VERIFICATION_INFO_REQUESTED', 'Additional Information Requested'), ('VERIFICATION_USER_RESPONDED', 'User Responded to Info Request'), ('SUBMISSION_RECEIVED', 'Submission Received'), ('REVIEW_ASSIGNED', 'Review Assigned'), ('REVIEW_COMPLETED', 'Review Completed'), ('DECISION_MADE', 'Editorial Decision'), ('REVIEW_INVITATION', 'Review Invitation'), ('REVIEW_REMINDER', 'Review Deadline Reminder'), ('REVIEW_SUBMITTED', 'Review Submitted Confirmation'), ('EDITORIAL_DECISION_ACCEPT', 'Manuscript Accepted'), ('EDITORIAL_DECISION_REJECT', 'Manuscript Rejected'), ('REVISION_REQUESTED', 'Revisions Requested'), ('DECISION_ACCEPT', 'Decision: Accepted'), ('DECISION_REJECT', 'Decision: Rejected'), ('DECISION_MINOR_REVISION', 'Decision: Minor Revision'), ('DECISION_MAJOR_REVISION', 'Decision: Major Revision'), ('REVISION_REQUEST', 'Revision Request'), ('REVISION_SUBMITTED', 'Revision Submitted (Editor Notification)'), ('REVISION_APPROVED', 'Revision Approved'), ('REVISION_REJECTED', 'Revision Rejected'), ('COPYEDITING_ASSIGNED', 'Copyediting Assignment'), ('COPYEDITING_STARTED', 'Copyediting Started'), ('COPYEDITING_COMPLETED', 'Copyediting Completed'), ('COPYEDITING_FILE_READY', 'Copyedited File Ready for Author Review'), ('PRODUCTION_ASSIGNED', 'Production Assignment'), ('PRODUCTION_STARTED', 'Production Started'), ('PRODUCTION_COMPLETED', 'Production Completed'), ('GALLEY_PUBLISHED', 'Galley Published'), ('PUBLICATION_SCHEDULED', 'Publication Scheduled'), ('PUBLICATION_PUBLISHED', 'Article Published'), ('PUBLICATION_CANCELLED', 'Publication Cancelled')], help_text='Type of email template', max_length=50, unique=True),
        ),
    ]
