from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_emailnotificationpreference_email_on_copyediting_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(
                choices=[
                    ('WELCOME', 'Welcome Email'),
                    ('EMAIL_VERIFICATION', 'Email Verification'),
                    ('PASSWORD_RESET', 'Password Reset'),
                    ('ORCID_CONNECTED', 'ORCID Connected'),
                    ('ORCID_DISCONNECTED', 'ORCID Disconnected'),
                    ('VERIFICATION_SUBMITTED', 'Verification Request Submitted'),
                    ('VERIFICATION_APPROVED', 'Verification Request Approved'),
                    ('VERIFICATION_REJECTED', 'Verification Request Rejected'),
                    ('VERIFICATION_INFO_REQUESTED', 'Additional Information Requested'),
                    ('VERIFICATION_USER_RESPONDED', 'User Responded to Info Request'),
                    ('SUBMISSION_RECEIVED', 'Submission Received'),
                    ('SUBMISSION_FIRST_ACKNOWLEDGEMENT', 'Submission First Acknowledgement'),
                    ('SUBMISSION_PRE_REVIEW_CORRECTION', 'Submission Pre-Review Correction'),
                    ('SUBMISSION_REVIEW_STARTED', 'Submission Review Started'),
                    ('SUBMISSION_COPYEDITING_DISCUSSION', 'Submission Copyediting Discussion'),
                    ('SUBMISSION_PRODUCTION_PROOFREADING', 'Submission Production Proofreading'),
                    ('EDITORIAL_ASSIGNMENT_SECTION_EDITOR', 'Editorial Assignment - Section Editor'),
                    ('EDITORIAL_ASSIGNMENT_GUEST_EDITOR', 'Editorial Assignment - Guest Editor'),
                    ('REVIEW_ASSIGNED', 'Review Assigned'),
                    ('REVIEW_COMPLETED', 'Review Completed'),
                    ('DECISION_MADE', 'Editorial Decision'),
                    ('REVIEW_INVITATION', 'Review Invitation'),
                    ('REVIEW_REMINDER', 'Review Deadline Reminder'),
                    ('REVIEW_SUBMITTED', 'Review Submitted Confirmation'),
                    ('EDITORIAL_DECISION_ACCEPT', 'Manuscript Accepted'),
                    ('EDITORIAL_DECISION_REJECT', 'Manuscript Rejected'),
                    ('REVISION_REQUESTED', 'Revisions Requested'),
                    ('DECISION_ACCEPT', 'Decision: Accepted'),
                    ('DECISION_REJECT', 'Decision: Rejected'),
                    ('DECISION_MINOR_REVISION', 'Decision: Minor Revision'),
                    ('DECISION_MAJOR_REVISION', 'Decision: Major Revision'),
                    ('REVISION_REQUEST', 'Revision Request'),
                    ('REVISION_SUBMITTED', 'Revision Submitted (Editor Notification)'),
                    ('REVISION_APPROVED', 'Revision Approved'),
                    ('REVISION_REJECTED', 'Revision Rejected'),
                    ('REVIEW_EDITORIAL_ASSIGNMENT', 'Review Editorial Assignment'),
                    ('REVIEW_ARTICLE_REQUEST', 'Review Article Request'),
                    ('REVIEW_UNABLE_TO_REVIEW', 'Review Unable to Review'),
                    ('REVIEW_REQUEST_CANCELLED', 'Review Request Cancelled'),
                    ('REVIEW_EDITOR_DECISION_NOTICE', 'Review Editor Decision Notice'),
                    ('COPYEDITING_ASSIGNED', 'Copyediting Assignment'),
                    ('COPYEDITING_EDITORIAL_ASSIGNMENT', 'Copyediting Editorial Assignment'),
                    ('COPYEDITING_REQUEST', 'Copyediting Request'),
                    ('COPYEDITING_STARTED', 'Copyediting Started'),
                    ('COPYEDITING_COMPLETED', 'Copyediting Completed'),
                    ('COPYEDITING_FILE_READY', 'Copyedited File Ready for Author Review'),
                    ('PRODUCTION_ASSIGNED', 'Production Assignment'),
                    ('PRODUCTION_STARTED', 'Production Started'),
                    ('PRODUCTION_COMPLETED', 'Production Completed'),
                    ('GALLEY_PUBLISHED', 'Galley Published'),
                    ('PUBLICATION_SCHEDULED', 'Publication Scheduled'),
                    ('PUBLICATION_PUBLISHED', 'Article Published'),
                    ('PUBLICATION_CANCELLED', 'Publication Cancelled'),
                ],
                help_text='Type of email template',
                max_length=50,
                unique=True,
            ),
        ),
    ]
